/**
 * This file EXPORTS a string (`HELPER_TEMPLATE`) that is written verbatim
 * to `_uat.ts` inside each generated test output folder. Generated Playwright
 * specs import from './_uat' and use `uat.click`, `uat.fill`, etc. instead of
 * raw `page.getByRole(...).click()`. The helper tries the deterministic
 * locator first; if it fails and self-healing is enabled (via env vars
 * injected by `runner.ts`), it takes a screenshot, asks a vision LLM
 * (Claude / Gemini / OpenAI) for a better locator and retries ONCE.
 *
 * The helper is self-contained — it only uses `@playwright/test` types and
 * native `fetch`. It must not import anything from the parent Electron app
 * because the spawned child process runs in a different module resolution
 * context.
 */
export const HELPER_FILENAME = '_uat.ts'

export const HELPER_TEMPLATE = `// AUTO-GENERATED by Salesforce UAT Auto-Runner. Do not edit by hand.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { expect, type FrameLocator, type Locator, type Page } from '@playwright/test'

type Action = 'click' | 'fill' | 'select' | 'press' | 'locate'

interface LocatorHint {
  strategy: 'role' | 'label' | 'text' | 'placeholder' | 'css' | 'xpath' | 'coordinates'
  role?: string
  name?: string
  exact?: boolean
  nth?: number
  selector?: string
  x?: number
  y?: number
  reasoning?: string
}

const fallbackCounter = { n: 0 }
const MAX_FALLBACKS = Number(process.env.SF_AI_MAX_FALLBACKS ?? '6')
const HEALING_ENABLED = process.env.SF_AI_HEALING_ENABLED === '1'
const AI_PROVIDER = (process.env.SF_AI_PROVIDER ?? '') as 'anthropic' | 'openai' | 'gemini' | ''
const AI_API_KEY = process.env.SF_AI_API_KEY ?? ''
const AI_MODEL = process.env.SF_AI_VISION_MODEL ?? process.env.SF_AI_MODEL ?? ''

/**
 * Presentation-pace settings. We intentionally pause BEFORE clicks and
 * visibility checks so the end user watching the browser can see what
 * Playwright is about to do, and BRIEFLY highlight the target element.
 * Typing (uat.fill) stays instant because watching each keystroke adds
 * no value and Salesforce re-renders on every keystroke in lwc fields,
 * which would make "slow typing" painful.
 */
const CLICK_PAUSE_MS = Number(process.env.SF_UAT_CLICK_PAUSE_MS ?? '700')
const POST_CLICK_PAUSE_MS = Number(process.env.SF_UAT_POST_CLICK_PAUSE_MS ?? '300')
const HIGHLIGHT_MS = Number(process.env.SF_UAT_HIGHLIGHT_MS ?? '700')

console.log(
  '[uat-pace] click=' + CLICK_PAUSE_MS + 'ms post=' + POST_CLICK_PAUSE_MS + 'ms highlight=' + HIGHLIGHT_MS + 'ms'
)

async function sleep(ms: number): Promise<void> {
  if (ms <= 0) return
  await new Promise((r) => setTimeout(r, ms))
}

/**
 * Scrolls the target into view and draws a blue outline around it for a
 * short moment, so a user watching the run can follow what is being
 * interacted with. Never throws — purely cosmetic.
 */
async function highlight(locator: Locator): Promise<void> {
  if (HIGHLIGHT_MS <= 0) return
  try {
    await locator.scrollIntoViewIfNeeded({ timeout: 1500 })
  } catch {
    // Element may not exist yet — let the caller handle that.
  }
  try {
    await locator.evaluate((el: Element, durationMs: number) => {
      const htmlEl = el as HTMLElement
      const prevOutline = htmlEl.style.outline
      const prevOffset = htmlEl.style.outlineOffset
      const prevBoxShadow = htmlEl.style.boxShadow
      const prevTransition = htmlEl.style.transition
      htmlEl.style.transition = 'outline 0.12s ease-in-out, box-shadow 0.12s ease-in-out'
      htmlEl.style.outline = '3px solid #2563eb'
      htmlEl.style.outlineOffset = '2px'
      htmlEl.style.boxShadow = '0 0 0 6px rgba(37, 99, 235, 0.25)'
      setTimeout(() => {
        htmlEl.style.outline = prevOutline
        htmlEl.style.outlineOffset = prevOffset
        htmlEl.style.boxShadow = prevBoxShadow
        htmlEl.style.transition = prevTransition
      }, durationMs)
    }, HIGHLIGHT_MS)
  } catch {
    // Shadow-DOM / cross-origin / detached — skip silently.
  }
}

const SYSTEM_PROMPT = \`You are a Playwright locator assistant for Salesforce Lightning. Given a screenshot and a natural-language description of the UI element the caller wants to interact with, respond ONLY with a single JSON object describing the best way to find that element with Playwright.

Valid response shapes:
{"strategy":"role","role":"button","name":"Exact accessible name","exact":true}
{"strategy":"label","name":"Exact visible label"}
{"strategy":"text","name":"Exact visible text","exact":false}
{"strategy":"placeholder","name":"Placeholder text"}
{"strategy":"css","selector":"CSS selector"}
{"strategy":"xpath","selector":"//xpath/here"}
{"strategy":"coordinates","x":842,"y":196}

Rules:
- Prefer role > label > text > placeholder > css > xpath > coordinates.
- "name" must be the EXACT visible string shown in the screenshot.
- If multiple elements share the same role+name, add "nth" (0-based) OR, much better, switch strategy to css with a scoping selector (e.g. "section[role=dialog] button.slds-button_brand").
- Never invent numeric IDs.
- DIVERSIFY between retries. If the FAILED ATTEMPTS list already contains a given strategy+name, pick a DIFFERENT strategy this turn. Never return a hint that is byte-identical to one that already failed.
- For Salesforce Lightning duplicates (Save, Cancel, New, Edit) PREFER a scoped css selector like "section[role=dialog] .modal-footer button.slds-button_brand" over nth().
- For record detail titles use "records-highlights-details-item lightning-formatted-name" or ".slds-page-header__name-title", never "h1".
- Respond with ONLY the JSON, no prose, no code fences.\`

function logHeal(message: string): void {
  // stdout so it appears in RunDetail.
  console.log('[uat-heal] ' + message)
}

async function screenshotBase64(page: Page): Promise<string> {
  const buf = await page.screenshot({ type: 'png', fullPage: false })
  return buf.toString('base64')
}

async function askVision(
  page: Page,
  description: string,
  action: Action,
  previous: string[]
): Promise<LocatorHint> {
  const imageB64 = await screenshotBase64(page)
  const userText = [
    'ACTION: ' + action,
    'TARGET DESCRIPTION: ' + description,
    'PAGE URL: ' + page.url(),
    previous.length ? 'FAILED ATTEMPTS:\\n' + previous.map((a) => '- ' + a).join('\\n') : '',
    'Respond with ONLY a JSON object matching the schema.'
  ]
    .filter(Boolean)
    .join('\\n')

  const raw = await callVisionApi(userText, imageB64)
  return parseVision(raw)
}

async function callVisionApi(userText: string, imageB64: string): Promise<string> {
  if (AI_PROVIDER === 'anthropic') return callAnthropic(userText, imageB64)
  if (AI_PROVIDER === 'openai') return callOpenAI(userText, imageB64)
  if (AI_PROVIDER === 'gemini') return callGemini(userText, imageB64)
  throw new Error('Unknown vision provider: ' + AI_PROVIDER)
}

async function callAnthropic(userText: string, imageB64: string): Promise<string> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': AI_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: AI_MODEL,
      max_tokens: 800,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'image',
              source: { type: 'base64', media_type: 'image/png', data: imageB64 }
            },
            { type: 'text', text: userText }
          ]
        }
      ]
    })
  })
  if (!res.ok) throw new Error('Anthropic vision error ' + res.status + ': ' + (await res.text()))
  const data: any = await res.json()
  const block = (data.content ?? []).find((b: any) => b.type === 'text')
  return block?.text ?? ''
}

async function callOpenAI(userText: string, imageB64: string): Promise<string> {
  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: 'Bearer ' + AI_API_KEY
    },
    body: JSON.stringify({
      model: AI_MODEL,
      max_tokens: 800,
      temperature: 0.1,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        {
          role: 'user',
          content: [
            { type: 'text', text: userText },
            { type: 'image_url', image_url: { url: 'data:image/png;base64,' + imageB64 } }
          ]
        }
      ]
    })
  })
  if (!res.ok) throw new Error('OpenAI vision error ' + res.status + ': ' + (await res.text()))
  const data: any = await res.json()
  return data.choices?.[0]?.message?.content ?? ''
}

async function callGemini(userText: string, imageB64: string): Promise<string> {
  const url =
    'https://generativelanguage.googleapis.com/v1beta/models/' +
    encodeURIComponent(AI_MODEL) +
    ':generateContent?key=' +
    encodeURIComponent(AI_API_KEY)
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      systemInstruction: { role: 'system', parts: [{ text: SYSTEM_PROMPT }] },
      contents: [
        {
          role: 'user',
          parts: [
            { inline_data: { mime_type: 'image/png', data: imageB64 } },
            { text: userText }
          ]
        }
      ],
      generationConfig: { temperature: 0.1, responseMimeType: 'application/json' }
    })
  })
  if (!res.ok) throw new Error('Gemini vision error ' + res.status + ': ' + (await res.text()))
  const data: any = await res.json()
  return data.candidates?.[0]?.content?.parts?.map((p: any) => p.text ?? '').join('') ?? ''
}

function parseVision(raw: string): LocatorHint {
  let text = raw.trim()
  if (text.startsWith('\\\`\\\`\\\`')) {
    text = text.replace(/^\\\`\\\`\\\`(?:json)?/i, '').replace(/\\\`\\\`\\\`$/, '').trim()
  }
  const first = text.indexOf('{')
  const last = text.lastIndexOf('}')
  if (first !== -1 && last > first) text = text.slice(first, last + 1)
  const parsed = JSON.parse(text) as LocatorHint
  if (!parsed || !parsed.strategy) throw new Error('Vision response missing strategy: ' + raw)
  return parsed
}

function buildLocator(page: Page, hint: LocatorHint): Locator | null {
  switch (hint.strategy) {
    case 'role': {
      if (!hint.role || !hint.name) return null
      const l = page.getByRole(hint.role as any, { name: hint.name, exact: hint.exact ?? false })
      return typeof hint.nth === 'number' ? l.nth(hint.nth) : l
    }
    case 'label':
      return hint.name ? page.getByLabel(hint.name, { exact: hint.exact ?? false }) : null
    case 'text':
      return hint.name ? page.getByText(hint.name, { exact: hint.exact ?? false }) : null
    case 'placeholder':
      return hint.name ? page.getByPlaceholder(hint.name) : null
    case 'css':
    case 'xpath':
      return hint.selector ? page.locator(hint.selector) : null
    case 'coordinates':
      return null
    default:
      return null
  }
}

async function applyHint(
  page: Page,
  hint: LocatorHint,
  action: Action,
  value?: string
): Promise<void> {
  if (hint.strategy === 'coordinates') {
    if (typeof hint.x !== 'number' || typeof hint.y !== 'number') {
      throw new Error('Vision returned coordinates without x/y')
    }
    if (action === 'click') {
      await page.mouse.click(hint.x, hint.y)
      return
    }
    if (action === 'fill' && typeof value === 'string') {
      await page.mouse.click(hint.x, hint.y)
      await page.keyboard.type(value)
      return
    }
    throw new Error('Coordinates fallback unsupported for action: ' + action)
  }
  const loc = buildLocator(page, hint)
  if (!loc) throw new Error('Could not build locator from vision hint: ' + JSON.stringify(hint))
  if (action === 'click') await loc.click({ timeout: 15000 })
  else if (action === 'fill' && typeof value === 'string') await robustFill(page, loc, value, 15000)
  else if (action === 'locate') await loc.waitFor({ state: 'visible', timeout: 15000 })
  else throw new Error('Unsupported action in applyHint: ' + action)
}

const MAX_VISION_ATTEMPTS_PER_CALL = 2

async function healAndRetry<T>(
  page: Page,
  description: string,
  action: Action,
  original: () => Promise<T>,
  apply: (hint: LocatorHint) => Promise<T>
): Promise<T> {
  if (!HEALING_ENABLED) throw new Error('[uat] primary locator failed and healing disabled: ' + description)
  if (!AI_PROVIDER || !AI_API_KEY || !AI_MODEL) {
    throw new Error('[uat] healing enabled but SF_AI_* env vars missing')
  }
  if (fallbackCounter.n >= MAX_FALLBACKS) {
    throw new Error('[uat] max vision fallbacks reached (' + MAX_FALLBACKS + ')')
  }
  fallbackCounter.n += 1
  logHeal('fallback #' + fallbackCounter.n + ' for: ' + description)
  const previous: string[] = []
  try {
    await original()
    return undefined as unknown as T
  } catch (firstErr) {
    previous.push('original locator: ' + String((firstErr as Error).message ?? firstErr).slice(0, 300))
  }

  let lastErr: Error | null = null
  for (let attempt = 1; attempt <= MAX_VISION_ATTEMPTS_PER_CALL; attempt++) {
    const hint = await askVision(page, description, action, previous)
    const hintKey = JSON.stringify(hint)
    logHeal('vision attempt ' + attempt + ' suggested: ' + hintKey)
    if (previous.some((p) => p.includes(hintKey))) {
      // Vision gave us a duplicate — signal more forcefully and bail.
      previous.push('duplicate suggestion: ' + hintKey)
      lastErr = new Error('Vision kept returning the same failing hint: ' + hintKey)
      continue
    }
    try {
      const result = await apply(hint)
      return result
    } catch (e) {
      lastErr = e as Error
      previous.push('attempt ' + attempt + ' hint ' + hintKey + ' failed: ' + String(lastErr.message ?? lastErr).slice(0, 200))
    }
  }
  throw lastErr ?? new Error('[uat] vision retries exhausted for: ' + description)
}

/**
 * Fill a Salesforce Lightning field in a way that actually sticks.
 *
 * Plain \`locator.fill(value)\` often silently no-ops when the matched
 * element is the outer \`lightning-input\` wrapper rather than the real
 * \`<input>\` inside its shadow/light DOM. When that happens Playwright
 * does not throw — the test just quietly moves on with an empty field
 * and Save fails down the line with "field is required".
 *
 * Strategy:
 *  1. Resolve the locator down to a concrete typable descendant
 *     (\`input\`, \`textarea\`, or \`[contenteditable="true"]\`) when the
 *     matched element itself is not typable.
 *  2. Click to focus, Ctrl/Cmd+A to select any existing value, then
 *     \`fill\` the full string in one shot (instant, but reliable).
 *  3. Verify via \`inputValue\` / \`textContent\` and retry with
 *     \`pressSequentially\` as a last resort.
 */
async function robustFill(
  page: Page,
  locator: Locator,
  value: string,
  timeout: number
): Promise<void> {
  const typable = await resolveTypableTarget(locator)
  try {
    await typable.click({ timeout })
  } catch {
    // Some Salesforce fields steal focus; proceed anyway.
  }
  try {
    const modifier = process.platform === 'darwin' ? 'Meta' : 'Control'
    await page.keyboard.press(modifier + '+A')
    await page.keyboard.press('Delete')
  } catch {
    // Ignore — we'll rely on fill() to overwrite.
  }
  try {
    await typable.fill(value, { timeout })
  } catch {
    // Fall through to sequential typing below.
  }
  const actual = await readFieldValue(typable).catch(() => '')
  if (actual === value) return
  try {
    await typable.focus({ timeout: 2000 })
  } catch {
    // Ignore focus errors.
  }
  await page.keyboard.type(value)
  const retry = await readFieldValue(typable).catch(() => '')
  if (retry === value) return
  throw new Error(
    'Failed to populate field (got ' +
      JSON.stringify(retry) +
      ', expected ' +
      JSON.stringify(value) +
      '). The locator probably matched a wrapper element instead of the real input.'
  )
}

/**
 * Given a locator that may point at a \`lightning-input\` / \`lightning-combobox\`
 * / label element, return a locator that points at a real typable
 * descendant. Falls back to the original locator when nothing matches.
 */
async function resolveTypableTarget(locator: Locator): Promise<Locator> {
  try {
    const tagName = await locator.evaluate((el) => (el as Element).tagName.toLowerCase())
    if (tagName === 'input' || tagName === 'textarea') return locator
    if (tagName === 'div') {
      const editable = await locator.evaluate((el) =>
        (el as HTMLElement).isContentEditable
      )
      if (editable) return locator
    }
  } catch {
    // If we can't evaluate, just search for a typable descendant below.
  }
  const descendant = locator.locator('input, textarea, [contenteditable="true"]').first()
  if (await descendant.count().catch(() => 0)) return descendant
  return locator
}

async function readFieldValue(locator: Locator): Promise<string> {
  try {
    return await locator.inputValue({ timeout: 1500 })
  } catch {
    // Content-editable / non-input elements.
  }
  try {
    return (await locator.textContent({ timeout: 1500 })) ?? ''
  } catch {
    return ''
  }
}

/**
 * When Salesforce shows a "Change Record Type" modal before the real
 * creation form, click "Next" automatically. The selector modal is
 * distinguishable from the real form because it has a "Next" button but
 * no "Save" button.
 */
async function handleRecordTypeSelectorIfPresent(page: Page): Promise<void> {
  const dialog = page.getByRole('dialog').last()
  if (!(await dialog.isVisible().catch(() => false))) return
  const nextBtn = dialog.getByRole('button', { name: /^(next|continue|επόμενο)$/i }).first()
  const saveBtn = dialog.getByRole('button', { name: /^(save|αποθήκευση)$/i }).first()
  const hasNext = (await nextBtn.count().catch(() => 0)) > 0
  const hasSave = (await saveBtn.count().catch(() => 0)) > 0
  if (hasNext && !hasSave) {
    console.log('[uat-openNew] record-type selector detected, clicking Next')
    await nextBtn.click({ timeout: 10000 }).catch(() => void 0)
    // Give Lightning a moment to swap in the real creation form.
    await page.waitForTimeout(800)
  }
}

/**
 * Cheap deterministic retries before burning a vision call. Salesforce
 * renders duplicates of common buttons (Save, Cancel, New) both inside
 * the modal AND on the background record page. Scoping to the top-most
 * visible dialog fixes the majority of strict-mode / nth() misses.
 */
async function scopedFallback(
  page: Page,
  action: Action,
  description: string,
  value?: string
): Promise<boolean> {
  const match = description.match(/['"]([^'"]+)['"]/)
  const name = match?.[1]?.trim()
  if (!name) return false
  const dialog = page.getByRole('dialog').last()
  if (!(await dialog.isVisible().catch(() => false))) return false
  try {
    if (action === 'click') {
      const btn = dialog.getByRole('button', { name, exact: true }).first()
      if (await btn.count() === 0) return false
      await btn.click({ timeout: 10000 })
      logHeal('scoped-fallback (dialog button "' + name + '") handled: ' + description)
      return true
    }
    if (action === 'fill' && typeof value === 'string') {
      const input = dialog.getByLabel(name).first()
      if (await input.count() === 0) return false
      await robustFill(page, input, value, 10000)
      logHeal('scoped-fallback (dialog label "' + name + '") handled: ' + description)
      return true
    }
    if (action === 'locate') {
      const el = dialog.getByText(name).first()
      if (await el.count() === 0) return false
      await el.waitFor({ state: 'visible', timeout: 10000 })
      logHeal('scoped-fallback (dialog text "' + name + '") handled: ' + description)
      return true
    }
  } catch {
    return false
  }
  return false
}

export const uat = {
  async click(
    page: Page,
    locator: Locator,
    opts: { description: string; timeout?: number }
  ): Promise<void> {
    try {
      await locator.waitFor({ state: 'visible', timeout: opts.timeout ?? 10000 })
      await highlight(locator)
      await sleep(CLICK_PAUSE_MS)
      await locator.click({ timeout: opts.timeout ?? 10000 })
      await sleep(POST_CLICK_PAUSE_MS)
      return
    } catch (err) {
      if (await scopedFallback(page, 'click', opts.description)) return
      await healAndRetry(
        page,
        opts.description,
        'click',
        async () => {
          throw err
        },
        async (hint) => {
          await applyHint(page, hint, 'click')
        }
      )
    }
  },
  async fill(
    page: Page,
    locator: Locator,
    value: string,
    opts: { description: string; timeout?: number }
  ): Promise<void> {
    try {
      await locator.waitFor({ state: 'visible', timeout: opts.timeout ?? 10000 })
      // Highlight so the user knows which field got filled, but no pause
      // before the fill itself — typing should be instant.
      await highlight(locator)
      await robustFill(page, locator, value, opts.timeout ?? 10000)
      return
    } catch (err) {
      if (await scopedFallback(page, 'fill', opts.description, value)) return
      await healAndRetry(
        page,
        opts.description,
        'fill',
        async () => {
          throw err
        },
        async (hint) => {
          await applyHint(page, hint, 'fill', value)
        }
      )
    }
  },
  async visible(
    page: Page,
    locator: Locator,
    opts: { description: string; timeout?: number }
  ): Promise<void> {
    try {
      await expect(locator).toBeVisible({ timeout: opts.timeout ?? 15000 })
      await highlight(locator)
      await sleep(CLICK_PAUSE_MS)
      return
    } catch (err) {
      if (await scopedFallback(page, 'locate', opts.description)) return
      await healAndRetry(
        page,
        opts.description,
        'locate',
        async () => {
          throw err
        },
        async (hint) => {
          await applyHint(page, hint, 'locate')
        }
      )
    }
  },

  /**
   * Returns a Locator scoped to the top-most visible Salesforce Lightning
   * modal. Use this for every click / fill that belongs to a "New" or
   * "Edit" modal so duplicate buttons on the background record page don't
   * trigger strict-mode violations.
   *
   *   const modal = uat.modal(page, 'New Contact')
   *   await uat.click(page, modal.getByRole('button', { name: 'Save', exact: true }), { description: 'Click "Save" in the "New Contact" modal' })
   */
  /**
   * Returns a Locator for the "creation/edit surface" — typically a modal
   * dialog, but transparently falls back to the full-page record-edit form
   * when the org has replaced the modal with a full-page experience. This
   * way, the same generated spec works for both classic and overridden
   * creation flows without branching.
   *
   * When a \`titleFragment\` is given, the helper prefers a dialog whose
   * header contains that text (e.g. "New Contact"). When no such dialog
   * exists, it returns whichever creation surface is currently visible.
   */
  modal(page: Page, titleFragment?: string): Locator {
    // The "creation/edit surface" in Salesforce can take several forms that
    // are VISUALLY almost identical but structurally very different. To
    // keep the generated specs readable ("modal.getByLabel('First Name')"),
    // we return a locator that matches whichever of these is on screen:
    //
    //   1. A standard Lightning dialog (role="dialog"). Classic modal.
    //   2. A Salesforce SLDS modal container (section.slds-modal__container
    //      — used by legacy overlays and some Console apps that don't set
    //      role="dialog" on the outer wrapper).
    //   3. A full-page lightning-record-edit-form (when the org replaced
    //      the modal with a full-page experience via page layout / override).
    //   4. A flexipage-based record-creation page (records-record-layout,
    //      records-record-creation, records-entity-edit-page).
    //   5. LAST RESORT: the records-recordedit component anywhere on the
    //      page. This covers Service Console + Agentforce workspaces where
    //      the creation form renders inside a Lightning workspace tab that
    //      does not expose role="dialog".
    const dialog = page.getByRole('dialog')
    const sldsModal = page.locator('section.slds-modal__container:visible').first()
    const lightningForm = page
      .locator(
        'lightning-record-edit-form, records-record-layout, records-record-creation, records-entity-edit-page, records-recordedit, records-form'
      )
      .first()
    // Workspace-tab creation surface: many Developer Edition orgs (and
    // orgs with Agentforce Studio or a Console app) open the "New Record"
    // form inside a [role="tabpanel"] inside <main>, WITHOUT a role=dialog
    // and WITHOUT a lightning-record-edit-form wrapper element. In that
    // case the form still has a "Save" button and a title heading, so we
    // scope to the active tabpanel that has those.
    const workspaceTab = page
      .locator('main [role="tabpanel"]')
      .filter({ has: page.getByRole('button', { name: /^(save|αποθήκευση)$/i }) })
      .last()
    // Last-resort surface: the <main> region. This always matches on a
    // Lightning page and lets label-based selectors find inputs even in
    // heavily customised orgs. It's intentionally broad — the calling
    // step's label text (e.g. "First Name") is specific enough to pick
    // the right input when the more targeted scopes above do not match.
    const mainRegion = page.getByRole('main').last()

    if (titleFragment) {
      const re = new RegExp(
        titleFragment.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&'),
        'i'
      )
      const scoped = dialog.filter({ hasText: re }).last()
      const scopedSlds = sldsModal.filter({ hasText: re })
      const scopedWorkspace = workspaceTab.filter({ hasText: re })
      return scoped.or(scopedSlds).or(scopedWorkspace).or(lightningForm).or(workspaceTab).or(mainRegion)
    }
    return dialog.last().or(sldsModal).or(lightningForm).or(workspaceTab).or(mainRegion)
  },

  /**
   * Locator for the primary title of a Salesforce record-detail page. Uses
   * Lightning-specific selectors that are stable across orgs; NEVER rely
   * on a bare page.locator('h1') — Lightning renders multiple h1 elements
   * (app name, breadcrumbs, list, …) and that will always strict-mode fail.
   */
  recordTitle(page: Page): Locator {
    return page
      .locator(
        'records-highlights-details-item lightning-formatted-name, ' +
          'records-entity-label, ' +
          '.slds-page-header__name-title, ' +
          'h1.slds-page-header__title'
      )
      .first()
  },

  /**
   * Locator for a heading on a Salesforce Setup / admin page (e.g. "Custom
   * Metadata Types", "Profiles", "Permission Sets"). Use this INSTEAD of
   * a bare \`page.getByRole('heading', ...)\` — Setup pages render several
   * headings (breadcrumb, section, content) so the first visible match is
   * what tests usually want.
   *
   *   await expect(uat.setupHeading(page, 'Custom Metadata Types')).toBeVisible()
   */
  setupHeading(page: Page, name: string): Locator {
    return page.getByRole('heading', { name, exact: true }).first()
  },

  /**
   * Navigate to a Setup page via the Setup → Quick Find flow. Works for
   * any standard Setup destination (Custom Metadata Types, Profiles,
   * Permission Sets, Object Manager, …) without hard-coding URLs that
   * change between Salesforce releases.
   *
   *   await uat.openSetupPage(page, 'Custom Metadata Types')
   *
   * After it returns, the Setup content area is scrolled to the target
   * entry and the entry has been clicked — you can then assert on
   * \`uat.setupHeading(page, ...)\`.
   */
  async openSetupPage(page: Page, quickFindName: string): Promise<void> {
    const origin = new URL(page.url()).origin
    // The canonical Setup landing URL: stable since LEX launched and
    // cheaper than clicking the gear icon every time.
    await page.goto(origin + '/lightning/setup/SetupOneHome/home')
    await page.waitForURL(/\\/lightning\\/setup\\//, { timeout: 60000 })
    await page.waitForLoadState('domcontentloaded')

    // Quick Find is inside an iframe on some orgs and in the main frame
    // on others, so try both.
    const quickFindScopes: Array<Page | FrameLocator> = [
      page,
      page.frameLocator('iframe').first()
    ]
    let filled = false
    for (const scope of quickFindScopes) {
      const box = scope
        .getByPlaceholder(/quick find|γρήγορη αναζήτηση/i)
        .first()
      if (await box.isVisible({ timeout: 3000 }).catch(() => false)) {
        await box.fill(quickFindName)
        filled = true
        break
      }
    }
    if (!filled) {
      throw new Error(
        '[uat.openSetupPage] Could not find the Quick Find box on the Setup page. URL=' +
          page.url()
      )
    }

    // Click the Quick Find result. Salesforce shows it as a link under
    // the matching section (Custom Code, Users, …).
    const exactRe = new RegExp(
      '^' + quickFindName.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&') + '$',
      'i'
    )
    for (const scope of quickFindScopes) {
      const link = scope.getByRole('link', { name: exactRe }).first()
      if (await link.isVisible({ timeout: 5000 }).catch(() => false)) {
        await link.click()
        await page.waitForLoadState('domcontentloaded')
        return
      }
    }
    throw new Error(
      '[uat.openSetupPage] Quick Find returned no link matching "' +
        quickFindName +
        '". Either the label is different in this org language, or the running user lacks access to that Setup entry.'
    )
  },

  /**
   * Waits until the browser is on a Lightning record-view URL for the
   * given sObject. Use AFTER a Save to confirm the record was created.
   *
   *   await uat.waitForRecordView(page, 'Contact')
   */
  async waitForRecordView(page: Page, apiName: string): Promise<void> {
    const re = new RegExp('/lightning/r/' + apiName + '/[0-9A-Za-z]{15,18}/view')
    await page.waitForURL(re, { timeout: 60000 })
  },

  /**
   * Navigate directly to the Lightning list view for the given object's
   * API name. Waits up to 60s for Salesforce's 302 redirect dance to
   * finish before returning.
   */
  async openList(page: Page, apiName: string): Promise<void> {
    const origin = new URL(page.url()).origin
    await page.goto(origin + '/lightning/o/' + apiName + '/list')
    const re = new RegExp('/lightning/o/' + apiName + '/list')
    await page.waitForURL(re, { timeout: 60000 })
  },

  /**
   * Navigate to the Lightning "new record" modal for the given object's API
   * name. Salesforce exposes three different flows depending on the object
   * and the running user's profile:
   *
   *   a) \`/lightning/o/<Api>/new\` → new-record modal opens immediately
   *      (most common case for standard objects).
   *   b) \`/lightning/o/<Api>/new\` → "Change Record Type" selector modal
   *      first, then Next → real new-record modal.
   *   c) URL hack silently bounces back to the list view (e.g. when the
   *      object has a custom layout override). In that case we open the
   *      list and click the "New" button ourselves.
   *
   * This helper tries (a) first, handles (b) automatically, and falls back
   * to (c) if the modal never appears — so the same generated spec works
   * across orgs with very different customisation.
   */
  async openNew(page: Page, apiName: string): Promise<void> {
    /**
     * Open the creation form by doing EXACTLY what a human user would do:
     *  1. Go to the object's list view.
     *  2. Click the "New" button on that list view's header.
     *  3. Wait for the creation form (modal or full-page) to appear.
     *
     * This helper deliberately does NOT try URL hacks like
     * /lightning/o/<Api>/new or ?nooverride=1 — those behave unpredictably
     * in orgs with Agentforce, Flow overrides, or custom page layouts, and
     * the end-user watching the browser sees apparent chaos ("it went to
     * a random page!") even when the automation eventually recovers.
     *
     * One deterministic path is better than five clever fallbacks.
     *
     * If the "New" button does not exist or does not produce a form, we
     * throw a clear error so the test is marked failed with an actionable
     * message instead of silently trying alternate routes.
     */
    const origin = new URL(page.url()).origin
    const listUrl = origin + '/lightning/o/' + apiName + '/list'

    // If we are not already on the list, navigate there. This keeps the
    // existing page context intact when the previous step already opened
    // the list (common in well-written test cases).
    if (!new RegExp('/lightning/o/' + apiName + '/list').test(page.url())) {
      await page.goto(listUrl)
      await page
        .waitForURL(new RegExp('/lightning/o/' + apiName + '/list'), { timeout: 60000 })
    }
    await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => void 0)

    const newRegex = /^\\s*(new|νέο|νέα)\\s*$/i
    // Prefer the button in the list-view header to avoid grabbing a
    // row-level "New Task" or related-list button.
    const headerButton = page
      .locator('force-listview-manager-header, div[role="banner"], .slds-page-header')
      .getByRole('button', { name: newRegex })
      .first()
    const anyButton = page.getByRole('button', { name: newRegex }).first()
    const newButton = (await headerButton.count().catch(() => 0)) > 0 ? headerButton : anyButton

    if (!(await newButton.isVisible().catch(() => false))) {
      throw new Error(
        '[uat.openNew] The "New" button is not visible on ' +
          apiName +
          ' list view. Either the running user lacks Create permission on ' +
          apiName +
          ', or the list view uses a custom dashboard/override that hides the standard button.'
      )
    }

    await newButton.click({ timeout: 15000 })

    // Wait for Salesforce to navigate to its creation URL. Clicking "New"
    // always flips the URL to /lightning/o/<Api>/new?... — regardless of
    // whether the final form renders as a modal, a Console subtab, or a
    // full-page flex layout. So we treat the URL change as the first,
    // cheapest signal.
    await page
      .waitForURL(new RegExp('/lightning/o/' + apiName + '/new\\\\b'), { timeout: 30000 })
      .catch(() => void 0)

    // Now wait for the form to be TRULY READY to accept input. We look
    // for a combination of signals that holds across every Salesforce UI
    // variant we've seen (Lightning Experience, Service Console, Agent
    // workspace, Agentforce-augmented orgs):
    //
    //   - At least 3 visible input/textarea/combobox elements
    //   - A visible "Save" button (or localized equivalent)
    //
    // We intentionally do NOT require role="dialog". In Service Console
    // and some Agentforce orgs the creation form is rendered full-viewport
    // without that role, and requiring it causes exactly the "stuck at
    // step 2" failure screenshots users report even though the form is
    // clearly on screen.
    const deadline = Date.now() + 45000
    let lastReport = 0
    while (Date.now() < deadline) {
      const visibleInputs = await page
        .locator('input:visible, textarea:visible, lightning-input:visible, lightning-combobox:visible')
        .count()
        .catch(() => 0)
      const saveButton = page.getByRole('button', { name: /^(save|αποθήκευση)$/i }).first()
      const hasSave = await saveButton.isVisible().catch(() => false)
      if (visibleInputs >= 3 && hasSave) {
        await handleRecordTypeSelectorIfPresent(page)
        return
      }
      // Periodically log what we're waiting for so the end user's run log
      // shows useful progress instead of silent failure.
      if (Date.now() - lastReport > 5000) {
        console.log(
          '[uat-openNew] waiting for ' +
            apiName +
            ' form (visible inputs=' +
            visibleInputs +
            ', save button=' +
            hasSave +
            ', url=' +
            page.url() +
            ')'
        )
        lastReport = Date.now()
      }
      await page.waitForTimeout(500)
    }

    // Diagnostic screenshot so the end user can see what the browser was
    // actually looking at when the helper gave up.
    try {
      await page.screenshot({ path: 'uat-openNew-failed-' + apiName + '.png', fullPage: true })
    } catch {
      // Screenshot failures shouldn't mask the real error.
    }
    throw new Error(
      '[uat.openNew] Clicked "New" on ' +
        apiName +
        ' list view but no fillable form appeared within 45s. Current URL: ' +
        page.url() +
        '. Open the saved screenshot uat-openNew-failed-' +
        apiName +
        '.png to see what was on screen — typical causes are a Flow/VF override or, rarely, an org whose New action doesn\\'t create a record at all.'
    )
  },

  /**
   * Logs the current \`page\` into Salesforce. Prefers the frontdoor fast path
   * (SF_SESSION_ID + SF_INSTANCE_URL, set by the parent runner after a SOAP
   * login); falls back to the standard username/password form if the session
   * is missing or frontdoor is disabled.
   *
   * Call as the very first step of any generated spec:
   *   await uat.login(page)
   *
   * After it resolves, the page is authenticated and sitting at
   * <instanceUrl>/lightning/page/home.
   */
  async login(page: Page): Promise<void> {
    const sessionId = process.env.SF_SESSION_ID ?? ''
    const instanceUrl = process.env.SF_INSTANCE_URL ?? ''
    const loginMode = process.env.SF_LOGIN_MODE ?? 'frontdoor'

    if (loginMode === 'frontdoor' && sessionId && instanceUrl) {
      const base = instanceUrl.replace(/\\/+$/, '')
      const retURL = encodeURIComponent('/lightning/page/home')
      const frontdoorUrl =
        base +
        '/secur/frontdoor.jsp?sid=' +
        encodeURIComponent(sessionId) +
        '&retURL=' +
        retURL
      await page.goto(frontdoorUrl, { waitUntil: 'commit' })
      try {
        await page.waitForURL(/\\/lightning\\//, { timeout: 60000 })
      } catch {
        await page.waitForLoadState('domcontentloaded', { timeout: 30000 })
      }
      await page.waitForLoadState('domcontentloaded')
      return
    }

    const username = process.env.SF_USERNAME ?? ''
    const password = process.env.SF_PASSWORD ?? ''
    const loginUrl = (process.env.SF_LOGIN_URL ?? 'https://login.salesforce.com').replace(
      /\\/+$/,
      ''
    )
    if (!username || !password) {
      throw new Error(
        '[uat.login] SF_USERNAME / SF_PASSWORD missing and no frontdoor session available'
      )
    }
    await page.goto(loginUrl + '/', { waitUntil: 'domcontentloaded' })
    await page.getByLabel('Username').fill(username)
    await page.getByLabel('Password').fill(password)
    await page.getByRole('button', { name: /log in/i }).click()
    await page.waitForURL(
      (u) =>
        /lightning\\.force\\.com/.test(u.hostname) ||
        (/my\\.salesforce\\.com/.test(u.hostname) && !/login/i.test(u.pathname)),
      { timeout: 60000 }
    )
    const errorLocator = page.locator('#error, .loginError, [id$=errorTitle]').first()
    if (await errorLocator.isVisible().catch(() => false)) {
      throw new Error(
        '[uat.login] Salesforce rejected the credentials: ' + (await errorLocator.textContent())
      )
    }
  }
}
`
