/**
 * This file EXPORTS a string (`HELPER_TEMPLATE`) that is written verbatim
 * to `_uat.ts` inside each generated test output folder. Generated Playwright
 * specs import from './_uat' and use `uat.click`, `uat.fill`, etc. instead of
 * raw `page.getByRole(...).click()`. The helper tries the deterministic
 * locator first; if it fails and self-healing is enabled (via env vars
 * injected by `runner.ts`), it takes a screenshot, asks a vision LLM
 * (Claude / Gemini / OpenAI) for a better locator and retries ONCE.
 *
 * The helper is self-contained — it only uses `@playwright/test` types and
 * native `fetch`. It must not import anything from the parent Electron app
 * because the spawned child process runs in a different module resolution
 * context.
 */
export const HELPER_FILENAME = '_uat.ts'

export const HELPER_TEMPLATE = `// AUTO-GENERATED by Salesforce UAT Auto-Runner. Do not edit by hand.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { expect, type Locator, type Page } from '@playwright/test'

type Action = 'click' | 'fill' | 'select' | 'press' | 'locate'

interface LocatorHint {
  strategy: 'role' | 'label' | 'text' | 'placeholder' | 'css' | 'xpath' | 'coordinates'
  role?: string
  name?: string
  exact?: boolean
  nth?: number
  selector?: string
  x?: number
  y?: number
  reasoning?: string
}

const fallbackCounter = { n: 0 }
const MAX_FALLBACKS = Number(process.env.SF_AI_MAX_FALLBACKS ?? '6')
const HEALING_ENABLED = process.env.SF_AI_HEALING_ENABLED === '1'
const AI_PROVIDER = (process.env.SF_AI_PROVIDER ?? '') as 'anthropic' | 'openai' | 'gemini' | ''
const AI_API_KEY = process.env.SF_AI_API_KEY ?? ''
const AI_MODEL = process.env.SF_AI_VISION_MODEL ?? process.env.SF_AI_MODEL ?? ''

const SYSTEM_PROMPT = \`You are a Playwright locator assistant for Salesforce Lightning. Given a screenshot and a natural-language description of the UI element the caller wants to interact with, respond ONLY with a single JSON object describing the best way to find that element with Playwright.

Valid response shapes:
{"strategy":"role","role":"button","name":"Exact accessible name","exact":true}
{"strategy":"label","name":"Exact visible label"}
{"strategy":"text","name":"Exact visible text","exact":false}
{"strategy":"placeholder","name":"Placeholder text"}
{"strategy":"css","selector":"CSS selector"}
{"strategy":"xpath","selector":"//xpath/here"}
{"strategy":"coordinates","x":842,"y":196}

Rules:
- Prefer role > label > text > placeholder > css > xpath > coordinates.
- "name" must be the EXACT visible string shown in the screenshot.
- If multiple elements share the same role+name, add "nth" (0-based) OR, much better, switch strategy to css with a scoping selector (e.g. "section[role=dialog] button.slds-button_brand").
- Never invent numeric IDs.
- DIVERSIFY between retries. If the FAILED ATTEMPTS list already contains a given strategy+name, pick a DIFFERENT strategy this turn. Never return a hint that is byte-identical to one that already failed.
- For Salesforce Lightning duplicates (Save, Cancel, New, Edit) PREFER a scoped css selector like "section[role=dialog] .modal-footer button.slds-button_brand" over nth().
- For record detail titles use "records-highlights-details-item lightning-formatted-name" or ".slds-page-header__name-title", never "h1".
- Respond with ONLY the JSON, no prose, no code fences.\`

function logHeal(message: string): void {
  // stdout so it appears in RunDetail.
  console.log('[uat-heal] ' + message)
}

async function screenshotBase64(page: Page): Promise<string> {
  const buf = await page.screenshot({ type: 'png', fullPage: false })
  return buf.toString('base64')
}

async function askVision(
  page: Page,
  description: string,
  action: Action,
  previous: string[]
): Promise<LocatorHint> {
  const imageB64 = await screenshotBase64(page)
  const userText = [
    'ACTION: ' + action,
    'TARGET DESCRIPTION: ' + description,
    'PAGE URL: ' + page.url(),
    previous.length ? 'FAILED ATTEMPTS:\\n' + previous.map((a) => '- ' + a).join('\\n') : '',
    'Respond with ONLY a JSON object matching the schema.'
  ]
    .filter(Boolean)
    .join('\\n')

  const raw = await callVisionApi(userText, imageB64)
  return parseVision(raw)
}

async function callVisionApi(userText: string, imageB64: string): Promise<string> {
  if (AI_PROVIDER === 'anthropic') return callAnthropic(userText, imageB64)
  if (AI_PROVIDER === 'openai') return callOpenAI(userText, imageB64)
  if (AI_PROVIDER === 'gemini') return callGemini(userText, imageB64)
  throw new Error('Unknown vision provider: ' + AI_PROVIDER)
}

async function callAnthropic(userText: string, imageB64: string): Promise<string> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': AI_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: AI_MODEL,
      max_tokens: 800,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'image',
              source: { type: 'base64', media_type: 'image/png', data: imageB64 }
            },
            { type: 'text', text: userText }
          ]
        }
      ]
    })
  })
  if (!res.ok) throw new Error('Anthropic vision error ' + res.status + ': ' + (await res.text()))
  const data: any = await res.json()
  const block = (data.content ?? []).find((b: any) => b.type === 'text')
  return block?.text ?? ''
}

async function callOpenAI(userText: string, imageB64: string): Promise<string> {
  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: 'Bearer ' + AI_API_KEY
    },
    body: JSON.stringify({
      model: AI_MODEL,
      max_tokens: 800,
      temperature: 0.1,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        {
          role: 'user',
          content: [
            { type: 'text', text: userText },
            { type: 'image_url', image_url: { url: 'data:image/png;base64,' + imageB64 } }
          ]
        }
      ]
    })
  })
  if (!res.ok) throw new Error('OpenAI vision error ' + res.status + ': ' + (await res.text()))
  const data: any = await res.json()
  return data.choices?.[0]?.message?.content ?? ''
}

async function callGemini(userText: string, imageB64: string): Promise<string> {
  const url =
    'https://generativelanguage.googleapis.com/v1beta/models/' +
    encodeURIComponent(AI_MODEL) +
    ':generateContent?key=' +
    encodeURIComponent(AI_API_KEY)
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      systemInstruction: { role: 'system', parts: [{ text: SYSTEM_PROMPT }] },
      contents: [
        {
          role: 'user',
          parts: [
            { inline_data: { mime_type: 'image/png', data: imageB64 } },
            { text: userText }
          ]
        }
      ],
      generationConfig: { temperature: 0.1, responseMimeType: 'application/json' }
    })
  })
  if (!res.ok) throw new Error('Gemini vision error ' + res.status + ': ' + (await res.text()))
  const data: any = await res.json()
  return data.candidates?.[0]?.content?.parts?.map((p: any) => p.text ?? '').join('') ?? ''
}

function parseVision(raw: string): LocatorHint {
  let text = raw.trim()
  if (text.startsWith('\\\`\\\`\\\`')) {
    text = text.replace(/^\\\`\\\`\\\`(?:json)?/i, '').replace(/\\\`\\\`\\\`$/, '').trim()
  }
  const first = text.indexOf('{')
  const last = text.lastIndexOf('}')
  if (first !== -1 && last > first) text = text.slice(first, last + 1)
  const parsed = JSON.parse(text) as LocatorHint
  if (!parsed || !parsed.strategy) throw new Error('Vision response missing strategy: ' + raw)
  return parsed
}

function buildLocator(page: Page, hint: LocatorHint): Locator | null {
  switch (hint.strategy) {
    case 'role': {
      if (!hint.role || !hint.name) return null
      const l = page.getByRole(hint.role as any, { name: hint.name, exact: hint.exact ?? false })
      return typeof hint.nth === 'number' ? l.nth(hint.nth) : l
    }
    case 'label':
      return hint.name ? page.getByLabel(hint.name, { exact: hint.exact ?? false }) : null
    case 'text':
      return hint.name ? page.getByText(hint.name, { exact: hint.exact ?? false }) : null
    case 'placeholder':
      return hint.name ? page.getByPlaceholder(hint.name) : null
    case 'css':
    case 'xpath':
      return hint.selector ? page.locator(hint.selector) : null
    case 'coordinates':
      return null
    default:
      return null
  }
}

async function applyHint(
  page: Page,
  hint: LocatorHint,
  action: Action,
  value?: string
): Promise<void> {
  if (hint.strategy === 'coordinates') {
    if (typeof hint.x !== 'number' || typeof hint.y !== 'number') {
      throw new Error('Vision returned coordinates without x/y')
    }
    if (action === 'click') {
      await page.mouse.click(hint.x, hint.y)
      return
    }
    if (action === 'fill' && typeof value === 'string') {
      await page.mouse.click(hint.x, hint.y)
      await page.keyboard.type(value)
      return
    }
    throw new Error('Coordinates fallback unsupported for action: ' + action)
  }
  const loc = buildLocator(page, hint)
  if (!loc) throw new Error('Could not build locator from vision hint: ' + JSON.stringify(hint))
  if (action === 'click') await loc.click({ timeout: 15000 })
  else if (action === 'fill' && typeof value === 'string') await loc.fill(value, { timeout: 15000 })
  else if (action === 'locate') await loc.waitFor({ state: 'visible', timeout: 15000 })
  else throw new Error('Unsupported action in applyHint: ' + action)
}

const MAX_VISION_ATTEMPTS_PER_CALL = 2

async function healAndRetry<T>(
  page: Page,
  description: string,
  action: Action,
  original: () => Promise<T>,
  apply: (hint: LocatorHint) => Promise<T>
): Promise<T> {
  if (!HEALING_ENABLED) throw new Error('[uat] primary locator failed and healing disabled: ' + description)
  if (!AI_PROVIDER || !AI_API_KEY || !AI_MODEL) {
    throw new Error('[uat] healing enabled but SF_AI_* env vars missing')
  }
  if (fallbackCounter.n >= MAX_FALLBACKS) {
    throw new Error('[uat] max vision fallbacks reached (' + MAX_FALLBACKS + ')')
  }
  fallbackCounter.n += 1
  logHeal('fallback #' + fallbackCounter.n + ' for: ' + description)
  const previous: string[] = []
  try {
    await original()
    return undefined as unknown as T
  } catch (firstErr) {
    previous.push('original locator: ' + String((firstErr as Error).message ?? firstErr).slice(0, 300))
  }

  let lastErr: Error | null = null
  for (let attempt = 1; attempt <= MAX_VISION_ATTEMPTS_PER_CALL; attempt++) {
    const hint = await askVision(page, description, action, previous)
    const hintKey = JSON.stringify(hint)
    logHeal('vision attempt ' + attempt + ' suggested: ' + hintKey)
    if (previous.some((p) => p.includes(hintKey))) {
      // Vision gave us a duplicate — signal more forcefully and bail.
      previous.push('duplicate suggestion: ' + hintKey)
      lastErr = new Error('Vision kept returning the same failing hint: ' + hintKey)
      continue
    }
    try {
      const result = await apply(hint)
      return result
    } catch (e) {
      lastErr = e as Error
      previous.push('attempt ' + attempt + ' hint ' + hintKey + ' failed: ' + String(lastErr.message ?? lastErr).slice(0, 200))
    }
  }
  throw lastErr ?? new Error('[uat] vision retries exhausted for: ' + description)
}

/**
 * Cheap deterministic retries before burning a vision call. Salesforce
 * renders duplicates of common buttons (Save, Cancel, New) both inside
 * the modal AND on the background record page. Scoping to the top-most
 * visible dialog fixes the majority of strict-mode / nth() misses.
 */
async function scopedFallback(
  page: Page,
  action: Action,
  description: string,
  value?: string
): Promise<boolean> {
  const match = description.match(/['"]([^'"]+)['"]/)
  const name = match?.[1]?.trim()
  if (!name) return false
  const dialog = page.getByRole('dialog').last()
  if (!(await dialog.isVisible().catch(() => false))) return false
  try {
    if (action === 'click') {
      const btn = dialog.getByRole('button', { name, exact: true }).first()
      if (await btn.count() === 0) return false
      await btn.click({ timeout: 10000 })
      logHeal('scoped-fallback (dialog button "' + name + '") handled: ' + description)
      return true
    }
    if (action === 'fill' && typeof value === 'string') {
      const input = dialog.getByLabel(name).first()
      if (await input.count() === 0) return false
      await input.fill(value, { timeout: 10000 })
      logHeal('scoped-fallback (dialog label "' + name + '") handled: ' + description)
      return true
    }
    if (action === 'locate') {
      const el = dialog.getByText(name).first()
      if (await el.count() === 0) return false
      await el.waitFor({ state: 'visible', timeout: 10000 })
      logHeal('scoped-fallback (dialog text "' + name + '") handled: ' + description)
      return true
    }
  } catch {
    return false
  }
  return false
}

export const uat = {
  async click(
    page: Page,
    locator: Locator,
    opts: { description: string; timeout?: number }
  ): Promise<void> {
    try {
      await locator.click({ timeout: opts.timeout ?? 10000 })
      return
    } catch (err) {
      if (await scopedFallback(page, 'click', opts.description)) return
      await healAndRetry(
        page,
        opts.description,
        'click',
        async () => {
          throw err
        },
        async (hint) => {
          await applyHint(page, hint, 'click')
        }
      )
    }
  },
  async fill(
    page: Page,
    locator: Locator,
    value: string,
    opts: { description: string; timeout?: number }
  ): Promise<void> {
    try {
      await locator.fill(value, { timeout: opts.timeout ?? 10000 })
      return
    } catch (err) {
      if (await scopedFallback(page, 'fill', opts.description, value)) return
      await healAndRetry(
        page,
        opts.description,
        'fill',
        async () => {
          throw err
        },
        async (hint) => {
          await applyHint(page, hint, 'fill', value)
        }
      )
    }
  },
  async visible(
    page: Page,
    locator: Locator,
    opts: { description: string; timeout?: number }
  ): Promise<void> {
    try {
      await expect(locator).toBeVisible({ timeout: opts.timeout ?? 15000 })
      return
    } catch (err) {
      if (await scopedFallback(page, 'locate', opts.description)) return
      await healAndRetry(
        page,
        opts.description,
        'locate',
        async () => {
          throw err
        },
        async (hint) => {
          await applyHint(page, hint, 'locate')
        }
      )
    }
  },

  /**
   * Returns a Locator scoped to the top-most visible Salesforce Lightning
   * modal. Use this for every click / fill that belongs to a "New" or
   * "Edit" modal so duplicate buttons on the background record page don't
   * trigger strict-mode violations.
   *
   *   const modal = uat.modal(page, 'New Contact')
   *   await uat.click(page, modal.getByRole('button', { name: 'Save', exact: true }), { description: 'Click "Save" in the "New Contact" modal' })
   */
  modal(page: Page, titleFragment?: string): Locator {
    const all = page.getByRole('dialog')
    if (!titleFragment) return all.last()
    const re = new RegExp(titleFragment.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&'), 'i')
    return all.filter({ hasText: re }).last()
  },

  /**
   * Locator for the primary title of a Salesforce record-detail page. Uses
   * Lightning-specific selectors that are stable across orgs; NEVER rely
   * on a bare page.locator('h1') — Lightning renders multiple h1 elements
   * (app name, breadcrumbs, list, …) and that will always strict-mode fail.
   */
  recordTitle(page: Page): Locator {
    return page
      .locator(
        'records-highlights-details-item lightning-formatted-name, ' +
          'records-entity-label, ' +
          '.slds-page-header__name-title, ' +
          'h1.slds-page-header__title'
      )
      .first()
  },

  /**
   * Waits until the browser is on a Lightning record-view URL for the
   * given sObject. Use AFTER a Save to confirm the record was created.
   *
   *   await uat.waitForRecordView(page, 'Contact')
   */
  async waitForRecordView(page: Page, apiName: string): Promise<void> {
    const re = new RegExp('/lightning/r/' + apiName + '/[0-9A-Za-z]{15,18}/view')
    await page.waitForURL(re, { timeout: 60000 })
  },

  /**
   * Navigate directly to the Lightning list view for the given object's
   * API name. Waits up to 60s for Salesforce's 302 redirect dance to
   * finish before returning.
   */
  async openList(page: Page, apiName: string): Promise<void> {
    const origin = new URL(page.url()).origin
    await page.goto(origin + '/lightning/o/' + apiName + '/list')
    const re = new RegExp('/lightning/o/' + apiName + '/list')
    await page.waitForURL(re, { timeout: 60000 })
  },

  /**
   * Navigate directly to the Lightning "new record" modal URL for the
   * given object's API name. Waits for the modal to become visible.
   */
  async openNew(page: Page, apiName: string): Promise<void> {
    const origin = new URL(page.url()).origin
    await page.goto(origin + '/lightning/o/' + apiName + '/new')
    await page.getByRole('dialog').last().waitFor({ state: 'visible', timeout: 60000 })
  },

  /**
   * Logs the current \`page\` into Salesforce. Prefers the frontdoor fast path
   * (SF_SESSION_ID + SF_INSTANCE_URL, set by the parent runner after a SOAP
   * login); falls back to the standard username/password form if the session
   * is missing or frontdoor is disabled.
   *
   * Call as the very first step of any generated spec:
   *   await uat.login(page)
   *
   * After it resolves, the page is authenticated and sitting at
   * <instanceUrl>/lightning/page/home.
   */
  async login(page: Page): Promise<void> {
    const sessionId = process.env.SF_SESSION_ID ?? ''
    const instanceUrl = process.env.SF_INSTANCE_URL ?? ''
    const loginMode = process.env.SF_LOGIN_MODE ?? 'frontdoor'

    if (loginMode === 'frontdoor' && sessionId && instanceUrl) {
      const base = instanceUrl.replace(/\\/+$/, '')
      const retURL = encodeURIComponent('/lightning/page/home')
      const frontdoorUrl =
        base +
        '/secur/frontdoor.jsp?sid=' +
        encodeURIComponent(sessionId) +
        '&retURL=' +
        retURL
      await page.goto(frontdoorUrl, { waitUntil: 'commit' })
      try {
        await page.waitForURL(/\\/lightning\\//, { timeout: 60000 })
      } catch {
        await page.waitForLoadState('domcontentloaded', { timeout: 30000 })
      }
      await page.waitForLoadState('domcontentloaded')
      return
    }

    const username = process.env.SF_USERNAME ?? ''
    const password = process.env.SF_PASSWORD ?? ''
    const loginUrl = (process.env.SF_LOGIN_URL ?? 'https://login.salesforce.com').replace(
      /\\/+$/,
      ''
    )
    if (!username || !password) {
      throw new Error(
        '[uat.login] SF_USERNAME / SF_PASSWORD missing and no frontdoor session available'
      )
    }
    await page.goto(loginUrl + '/', { waitUntil: 'domcontentloaded' })
    await page.getByLabel('Username').fill(username)
    await page.getByLabel('Password').fill(password)
    await page.getByRole('button', { name: /log in/i }).click()
    await page.waitForURL(
      (u) =>
        /lightning\\.force\\.com/.test(u.hostname) ||
        (/my\\.salesforce\\.com/.test(u.hostname) && !/login/i.test(u.pathname)),
      { timeout: 60000 }
    )
    const errorLocator = page.locator('#error, .loginError, [id$=errorTitle]').first()
    if (await errorLocator.isVisible().catch(() => false)) {
      throw new Error(
        '[uat.login] Salesforce rejected the credentials: ' + (await errorLocator.textContent())
      )
    }
  }
}
`
